<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\Hospitaly.Common.Infrastructure\Hospitaly.Common.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Cliniks\Hospitaly.Modules.Clinic.Infrastructure\Hospitaly.Modules.Clinic.Infrastructure.csproj" />
      <ProjectReference Include="..\Hospitaly.Modules.Users.Application\Hospitaly.Modules.Users.Application.csproj" />
      <ProjectReference Include="..\Hospitaly.Modules.Users.Presentation\Hospitaly.Modules.Users.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Database\Migrations\" />
    </ItemGroup>



</Project>
