// <auto-generated />
using System;
using Hospitaly.Modules.Clinic.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospitaly.Modules.Clinic.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ClinikDbContext))]
    [Migration("20260512121630_modifyClinicOperatingHours")]
    partial class modifyClinicOperatingHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clinics")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Appointment.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "ClinicId");

                    b.ToTable("Appointments", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Clinics", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.ClinicOwnerShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerShipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SharePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicOwnerships", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.ClinicSpecialty", b =>
                {
                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("ClinicId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("ClinicSpecialties", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Code");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.OperatingLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdministrativeStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .IsUnique();

                    b.ToTable("OperatingLicenses", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.ClinicAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("TerminatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ClinicId", "DoctorId");

                    b.ToTable("ClinicAffiliations", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Doctors", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.DoctorCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("DoctorCredentials", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.DoctorSpecialty", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CertifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("DoctorId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("DoctorSpecialties", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedules", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.ScheduleBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("DoctorScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxAppointmentsAllowed")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoctorScheduleId");

                    b.ToTable("ScheduleBlocks", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Patient.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Patients", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Room.MaintenanceBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduledBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("MaintenanceBlocks", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Room.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("Specialties", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.StaffMember.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("StaffMembers", "clinics");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Appointment.Appointment", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "DateTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("TimeSlotAppointmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("TimeSlotAppointmentId");

                                    b2.ToTable("Appointments", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeSlotAppointmentId");
                                });

                            b1.Navigation("DateTimeRange")
                                .IsRequired();
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.AppointmentStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("SetAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.AppointmentType", "AppointmentType", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("ExpectedDuration")
                                .HasColumnType("interval");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.CancellationDetails", "Cancellation", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CancelledAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("InitiatedBy")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.RescheduleInfo", "RescheduleInfo", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("RequestedBy")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("RescheduledAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Appointment.ValueObjects.TimeSlot", "OriginalTimeSlot", b2 =>
                                {
                                    b2.Property<Guid>("RescheduleInfoAppointmentId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RescheduleInfoAppointmentId");

                                    b2.ToTable("Appointments", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("RescheduleInfoAppointmentId");

                                    b2.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "DateTimeRange", b3 =>
                                        {
                                            b3.Property<Guid>("TimeSlotRescheduleInfoAppointmentId")
                                                .HasColumnType("uuid");

                                            b3.Property<DateTimeOffset?>("End")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<DateTimeOffset>("Start")
                                                .HasColumnType("timestamp with time zone");

                                            b3.HasKey("TimeSlotRescheduleInfoAppointmentId");

                                            b3.ToTable("Appointments", "clinics");

                                            b3.WithOwner()
                                                .HasForeignKey("TimeSlotRescheduleInfoAppointmentId");
                                        });

                                    b2.Navigation("DateTimeRange")
                                        .IsRequired();
                                });

                            b1.Navigation("OriginalTimeSlot")
                                .IsRequired();
                        });

                    b.Navigation("AppointmentType")
                        .IsRequired();

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Cancellation");

                    b.Navigation("RescheduleInfo");

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ClinicId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ClinicId");

                            b1.ToTable("Clinics", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.ClinicAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClinicId")
                                .HasColumnType("uuid");

                            b1.HasKey("ClinicId");

                            b1.ToTable("Clinics", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.Address", "Value", b2 =>
                                {
                                    b2.Property<Guid>("ClinicAddressClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.HasKey("ClinicAddressClinicId");

                                    b2.ToTable("Clinics", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicAddressClinicId");
                                });

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("ClinicAddressClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("ClinicAddressClinicId");

                                    b2.ToTable("Clinics", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicAddressClinicId");
                                });

                            b1.Navigation("Coordinates");

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.ClinicContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Website")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("ClinicId");

                            b1.ToTable("Clinics", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ClinicContactInfoClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Email");

                                    b2.HasKey("ClinicContactInfoClinicId");

                                    b2.ToTable("Clinics", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicContactInfoClinicId");
                                });

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("ClinicContactInfoClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("PhoneNumber");

                                    b2.HasKey("ClinicContactInfoClinicId");

                                    b2.ToTable("Clinics", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicContactInfoClinicId");
                                });

                            b1.Navigation("Email");

                            b1.Navigation("PhoneNumber");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.ClinicInfo", "Info", b1 =>
                        {
                            b1.Property<Guid>("ClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("TradingName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("ClinicId");

                            b1.ToTable("Clinics", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");
                        });

                    b.OwnsMany("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.OperatingHours", "OperatingHours", b1 =>
                        {
                            b1.Property<Guid>("ClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Day")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Day");

                            b1.HasKey("ClinicId", "Day");

                            b1.ToTable("ClinicOperatingHours", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicId");

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.OperatingTimeRange", "Hours", b2 =>
                                {
                                    b2.Property<Guid>("OperatingHoursClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("OperatingHoursDay")
                                        .HasColumnType("character varying(20)");

                                    b2.Property<bool>("_isActive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("HoursActive");

                                    b2.HasKey("OperatingHoursClinicId", "OperatingHoursDay");

                                    b2.ToTable("ClinicOperatingHours", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingHoursClinicId", "OperatingHoursDay");

                                    b2.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("OperatingTimeRangeOperatingHoursClinicId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("OperatingTimeRangeOperatingHoursDay")
                                                .HasColumnType("character varying(20)");

                                            b3.Property<DateTimeOffset?>("End")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("CloseTime");

                                            b3.Property<DateTimeOffset>("Start")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("OpenTime");

                                            b3.HasKey("OperatingTimeRangeOperatingHoursClinicId", "OperatingTimeRangeOperatingHoursDay");

                                            b3.ToTable("ClinicOperatingHours", "clinics");

                                            b3.WithOwner()
                                                .HasForeignKey("OperatingTimeRangeOperatingHoursClinicId", "OperatingTimeRangeOperatingHoursDay");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.OperatingTimeRange", "RestingTime", b2 =>
                                {
                                    b2.Property<Guid>("OperatingHoursClinicId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("OperatingHoursDay")
                                        .HasColumnType("character varying(20)");

                                    b2.Property<bool>("_isActive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RestingTimeActive");

                                    b2.HasKey("OperatingHoursClinicId", "OperatingHoursDay");

                                    b2.ToTable("ClinicOperatingHours", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingHoursClinicId", "OperatingHoursDay");

                                    b2.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("OperatingTimeRangeOperatingHoursClinicId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("OperatingTimeRangeOperatingHoursDay")
                                                .HasColumnType("character varying(20)");

                                            b3.Property<DateTimeOffset?>("End")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("RestingEndTime");

                                            b3.Property<DateTimeOffset>("Start")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("RestingStartTime");

                                            b3.HasKey("OperatingTimeRangeOperatingHoursClinicId", "OperatingTimeRangeOperatingHoursDay");

                                            b3.ToTable("ClinicOperatingHours", "clinics");

                                            b3.WithOwner()
                                                .HasForeignKey("OperatingTimeRangeOperatingHoursClinicId", "OperatingTimeRangeOperatingHoursDay");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.Navigation("Hours");

                            b1.Navigation("RestingTime");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.ClinicOwnerShip", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", null)
                        .WithMany("_ownerships")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ClinicOwnerShipId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ClinicOwnerShipId");

                            b1.ToTable("ClinicOwnerships", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicOwnerShipId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.OwnershipEffectiveRange", "OwnershipEffectivePeriod", b1 =>
                        {
                            b1.Property<Guid>("ClinicOwnerShipId")
                                .HasColumnType("uuid");

                            b1.HasKey("ClinicOwnerShipId");

                            b1.ToTable("ClinicOwnerships", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicOwnerShipId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Range", b2 =>
                                {
                                    b2.Property<Guid>("OwnershipEffectiveRangeClinicOwnerShipId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("OwnershipEffectiveRangeClinicOwnerShipId");

                                    b2.ToTable("ClinicOwnerships", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnershipEffectiveRangeClinicOwnerShipId");
                                });

                            b1.Navigation("Range")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("OwnershipEffectivePeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.ClinicSpecialty", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.Department", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DepartmentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.OperatingLicense", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", null)
                        .WithOne("OperatingLicense")
                        .HasForeignKey("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.OperatingLicense", "ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("OperatingLicenseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("OperatingLicenseId");

                            b1.ToTable("OperatingLicenses", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("OperatingLicenseId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.LicenceValidityPeriod", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("OperatingLicenseId")
                                .HasColumnType("uuid");

                            b1.HasKey("OperatingLicenseId");

                            b1.ToTable("OperatingLicenses", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("OperatingLicenseId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b2 =>
                                {
                                    b2.Property<Guid>("LicenceValidityPeriodOperatingLicenseId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("LicenceValidityPeriodOperatingLicenseId");

                                    b2.ToTable("OperatingLicenses", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("LicenceValidityPeriodOperatingLicenseId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.ClinicAffiliation", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", "Doctor")
                        .WithMany("_affiliations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ClinicAffiliationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ClinicAffiliationId");

                            b1.ToTable("ClinicAffiliations", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicAffiliationId");
                        });

                    b.OwnsMany("Hospitaly.Modules.Clinic.Domain.Doctor.ValueObjects.Privilege", "_grantedPrivileges", b1 =>
                        {
                            b1.Property<Guid>("ClinicAffiliationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("GrantedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("GrantedBy")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("ClinicAffiliationId", "Id");

                            b1.ToTable("ClinicAffiliationPrivileges", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ClinicAffiliationId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("_grantedPrivileges");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DoctorId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DoctorId");

                            b1.ToTable("Doctors", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("DoctorId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.DoctorCredential", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", null)
                        .WithMany("_credentials")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DoctorCredentialId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DoctorCredentialId");

                            b1.ToTable("DoctorCredentials", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("DoctorCredentialId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Doctor.ValueObjects.CredentialValidityPeriod", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("DoctorCredentialId")
                                .HasColumnType("uuid");

                            b1.HasKey("DoctorCredentialId");

                            b1.ToTable("DoctorCredentials", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("DoctorCredentialId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b2 =>
                                {
                                    b2.Property<Guid>("CredentialValidityPeriodDoctorCredentialId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("CredentialValidityPeriodDoctorCredentialId");

                                    b2.ToTable("DoctorCredentials", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("CredentialValidityPeriodDoctorCredentialId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.DoctorSpecialty", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.DoctorSchedule", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DoctorScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DoctorScheduleId");

                            b1.ToTable("DoctorSchedules", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("DoctorScheduleId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.ScheduleBlock", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.DoctorSchedule", null)
                        .WithMany("_blocks")
                        .HasForeignKey("DoctorScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ScheduleBlockId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ScheduleBlockId");

                            b1.ToTable("ScheduleBlocks", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleBlockId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("ScheduleBlockId")
                                .HasColumnType("uuid");

                            b1.HasKey("ScheduleBlockId");

                            b1.ToTable("ScheduleBlocks", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleBlockId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b2 =>
                                {
                                    b2.Property<Guid>("TimeRangeScheduleBlockId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("TimeRangeScheduleBlockId");

                                    b2.ToTable("ScheduleBlocks", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("TimeRangeScheduleBlockId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Patient.Patient", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Patient.ValueObjects.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPatientId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.HasKey("ContactInfoPatientId");

                                    b2.ToTable("Patients", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPatientId");
                                });

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPatientId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Email");

                                    b2.HasKey("ContactInfoPatientId");

                                    b2.ToTable("Patients", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPatientId");
                                });

                            b1.OwnsOne("Hospitaly.Modules.Clinic.Domain.Clinic.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoPatientId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("PhoneNumber");

                                    b2.HasKey("ContactInfoPatientId");

                                    b2.ToTable("Patients", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoPatientId");
                                });

                            b1.Navigation("Address");

                            b1.Navigation("Email");

                            b1.Navigation("PhoneNumber");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Patient.ValueObjects.InsuranceInfo", "Insurance", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GroupNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("InsurerName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PolicyNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");

                            b1.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "Value", b2 =>
                                {
                                    b2.Property<Guid>("InsuranceInfoPatientId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset?>("End")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("InsuranceInfoPatientId");

                                    b2.ToTable("Patients", "clinics");

                                    b2.WithOwner()
                                        .HasForeignKey("InsuranceInfoPatientId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Patient.ValueObjects.PatientIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("PatientId");

                            b1.HasIndex("NationalId");

                            b1.ToTable("Patients", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Patient.ValueObjects.PatientType", "PatientType", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("RegistrationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("PatientId");

                            b1.ToTable("Patients", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Identity")
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("PatientType")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Room.MaintenanceBlock", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Room.Room", null)
                        .WithMany("_maintenanceBlocks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceBlockId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MaintenanceBlockId");

                            b1.ToTable("MaintenanceBlocks", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceBlockId");
                        });

                    b.OwnsOne("Hospitaly.Common.Domain.Common.ValueObjects.DateTimeRange", "MaintenancePeriod", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceBlockId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MaintenanceBlockId");

                            b1.ToTable("MaintenanceBlocks", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceBlockId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("MaintenancePeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Room.Room", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Hospitaly.Modules.Clinic.Domain.Room.ValueObjects.RoomCapability", "_capabilities", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("RoomId", "Id");

                            b1.ToTable("RoomCapabilities", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.Room.ValueObjects.RoomType", "RoomType", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("RoomType")
                        .IsRequired();

                    b.Navigation("_capabilities");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", b =>
                {
                    b.HasOne("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("SpecialtyId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SpecialtyId");

                            b1.ToTable("Specialties", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("SpecialtyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.StaffMember.StaffMember", b =>
                {
                    b.OwnsOne("Hospitaly.Common.Domain.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.StaffMember.ValueObjects.EmploymentInfo", "Employment", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContractType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("HireDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("Hospitaly.Modules.Clinic.Domain.StaffMember.ValueObjects.StaffRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers", "clinics");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("Employment")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Clinic", b =>
                {
                    b.Navigation("OperatingLicense")
                        .IsRequired();

                    b.Navigation("_ownerships");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Clinic.Entities.Department", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Doctor.Doctor", b =>
                {
                    b.Navigation("_affiliations");

                    b.Navigation("_credentials");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.DoctorSchedule.DoctorSchedule", b =>
                {
                    b.Navigation("_blocks");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Room.Room", b =>
                {
                    b.Navigation("_maintenanceBlocks");
                });

            modelBuilder.Entity("Hospitaly.Modules.Clinic.Domain.Specialty.Specialty", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
